"""
R-dependence study for the 1D nonlinear advection test (Case B).

This script runs the KvN-QSVT pipeline of the paper (num_grid = 8, m = 2,
tau = 1, Lambda = 1, N_t = 210; identical to Case B) for several values of
the QSVT truncation index R, using phase factors generated by
qsvt_phase_generation_1D.py, and compares the results with

  (i)  the exact per-step propagator exp(-i H~ tau) applied with *identical
       state handling* to KvN-QSVT (direct propagation of the quantum state
       with per-step renormalization, no classical re-encoding) --- this is
       the R -> infinity limit of the KvN-QSVT pipeline; and
  (ii) the stored KvN-expm reference of the paper (which additionally
       re-encodes the classical variables after every step).

Outputs
  output/CaseBC/1DAdvectionTest_qsvt_u_numgrid_8_nx_8_delta_x_1_T_210_delta_t_1_m_2_R{R}.npy
  output/CaseBC/1DAdvectionTest_qsvt_E_numgrid_8_nx_8_delta_x_1_T_210_delta_t_1_m_2_R{R}.npy
  output/CaseBC/1DAdvectionTest_qsvt_R_dependence.pdf   (new figure of the revised paper)

Run  `python qsvt_phase_generation_1D.py`  first (creates output/qsvt_phases/).

Usage:  python qsvt_R_sweep_1D_caseB.py
"""
import csv
import math
import sys
import time

import matplotlib.pyplot as plt
import numpy as np
from qulacs import QuantumCircuit as QulacsCircuit
from scipy.linalg import eigh

from sub_function_1D import (Hamiltonian_matrix, U_Hamiltonian_matrix, V_gate,
                             initialize_quantum_state, normalize_matrix,
                             state_preparation, statevector_measurement)

# ----------------------- Case-B parameters (paper) -------------------------
tau = 1
Total_steps = 210
num_grid = 8
delta_x = 1
Lambda = 1
density = 1
epsilon_0 = 1
mass = 100
q = -1
N = 2 * num_grid
m = 2
M = math.comb(m + N, m)
n_x = math.floor(np.log2(M)) + 1
n_a = 1
R_LIST = [3, 5, 7, 9]
PHASE_DIR = "output/qsvt_phases"

k_wave = 2 * np.pi / num_grid
r = np.linspace(-num_grid / 2, num_grid / 2, num_grid)
u0 = np.sin(-k_wave * r)
E0 = np.zeros(num_grid)
EXTRACT = np.pi ** (2 * num_grid / 4) / 2 ** 0.5  # * norm_psi / Lambda later


def load_phi(path):
    with open(path) as f:
        row = next(csv.reader(f))
    return [float(s) for s in row]


def run_qsvt(cos_phi_vec, sin_phi_vec, U):
    """HS_TestSim_U_Hamiltonian_matrix with injectable phase vectors."""
    u = np.zeros((num_grid, Total_steps + 1))
    E = np.zeros((num_grid, Total_steps + 1))
    u[:, 0] = u0
    x = np.concatenate((u[:, 0], E[:, 0]))
    psi0, norm_psi = state_preparation(2 * num_grid, M, x, Lambda)
    num_qubits = 1 + 1 + n_a + n_x
    qs = initialize_quantum_state(n_a, num_qubits, psi0)
    qc = QulacsCircuit(num_qubits)
    qc.update_quantum_state(qs)
    for t in range(1, Total_steps + 1):
        V_gate(qc, n_a, n_x, U, cos_phi_vec, sin_phi_vec)
        psi_t = statevector_measurement(n_x, qc, qs)
        norm = np.sqrt(np.sum(np.abs(psi_t) ** 2))
        qc = QulacsCircuit(num_qubits)
        qs.set_zero_state()
        qs = initialize_quantum_state(n_a, num_qubits, psi_t / norm)
        qc.update_quantum_state(qs)
        data = psi_t * norm_psi / Lambda * EXTRACT * 2  # undo the 1/2 block
        u[:, t] = data[1:num_grid + 1]
        E[:, t] = data[num_grid + 1:2 * num_grid + 1]
    return u, E


def run_exact_direct(H_norm):
    """Exact per-step propagator with the same state handling as KvN-QSVT."""
    ev, V = eigh(H_norm)
    x = np.concatenate((u0, E0))
    psi, norm_psi = state_preparation(2 * num_grid, M, x, Lambda)
    psi = psi[:M].astype(complex)
    u = np.zeros((num_grid, Total_steps + 1))
    E = np.zeros((num_grid, Total_steps + 1))
    u[:, 0] = u0
    c = V.conj().T @ psi
    for t in range(1, Total_steps + 1):
        psi_t = (V @ (np.exp(-1j * ev * t) * c)).real
        psi_t = psi_t / np.linalg.norm(psi_t)
        data = psi_t * norm_psi / Lambda * EXTRACT
        u[:, t] = data[1:num_grid + 1]
        E[:, t] = data[num_grid + 1:2 * num_grid + 1]
    return u, E


def main():
    print("Building Hamiltonian and block encoding ...")
    H = Hamiltonian_matrix(delta_x, Lambda, density, epsilon_0, mass, q,
                           m, num_grid)
    H_norm, alpha = normalize_matrix(H)
    U, _ = U_Hamiltonian_matrix(delta_x, Lambda, density, epsilon_0, mass, q,
                                m, num_grid)
    t_phys = np.arange(Total_steps + 1) * tau / alpha
    wt = abs(np.sqrt(density / (epsilon_0 * mass)) * q) * t_phys
    print(f"alpha = ||H||_F = {alpha:.4f};  real-time step = {1/alpha:.4f}")

    # exact-direct reference (R -> infinity limit of the QSVT pipeline)
    u_dir, E_dir = run_exact_direct(H_norm)
    x_dir = np.vstack([u_dir, E_dir])

    # stored KvN-expm reference of the paper (per-step re-encoding)
    base = ("output/CaseBC/1DAdvectionTest_expm_{}_numgrid_8_nx_8_delta_x_1"
            "_T_210_delta_t_1_m_2.npy")
    x_exp = np.vstack([np.load(base.format("u")), np.load(base.format("E"))])

    # harness validation: original shipped phase files reproduce stored data
    u_o, E_o = run_qsvt(load_phi("output/cos1x.csv"),
                        load_phi("output/sin1x.csv"), U)
    x_orig = np.vstack([u_o, E_o])
    qbase = ("output/CaseBC/1DAdvectionTest_qsvt_{}_numgrid_8_nx_8_delta_x_1"
             "_T_210_delta_t_1_m_2.npy")
    x_store = np.vstack([np.load(qbase.format("u")), np.load(qbase.format("E"))])
    print("harness check |run(original csv) - stored qsvt npy|_max =",
          f"{np.max(np.abs(x_orig - x_store)):.3e}")

    results = {}
    reuse = "reuse" in sys.argv[1:]
    for R in R_LIST:
        t0 = time.time()
        paths = ["output/CaseBC/1DAdvectionTest_qsvt_"
                 f"{nm}_numgrid_8_nx_8_delta_x_1_T_210_delta_t_1_m_2_R{R}.npy"
                 for nm in ("u", "E")]
        if reuse:
            try:
                u_R, E_R = np.load(paths[0]), np.load(paths[1])
                results[R] = np.vstack([u_R, E_R])
                print(f"R={R}: loaded saved data")
                continue
            except FileNotFoundError:
                pass
        cp = load_phi(f"{PHASE_DIR}/cos1x_R{R}.csv")
        sp = load_phi(f"{PHASE_DIR}/sin1x_R{R}.csv")
        u_R, E_R = run_qsvt(cp, sp, U)
        for p, arr in zip(paths, (u_R, E_R)):
            np.save(p, arr)
        results[R] = np.vstack([u_R, E_R])
        print(f"R={R}: done [{time.time()-t0:.1f}s]")

    # ---------------- metrics ----------------
    nrm = np.linalg.norm
    def dev(a, b):
        return nrm(a - b, axis=0) / nrm(b, axis=0)
    def Delta(a):
        n = nrm(a, axis=0)
        return np.abs(n - n[0])

    print("\nmax_t ||x_R - x_direct|| / ||x_direct||  (t in (0, 100]):")
    lines = {}
    for lbl, x in [("orig(R=2 files)", x_orig)] + \
                  [(f"R={R}", results[R]) for R in R_LIST]:
        d = dev(x, x_dir)
        lines[lbl] = d
        print(f"  {lbl:16s}: max={np.max(d[1:]):.3e}  final={d[-1]:.3e}")
    print("context: max_t ||x_direct - x_expm(re-enc)||/||x_expm|| =",
          f"{np.max(dev(x_dir, x_exp)[1:]):.3e}")

    # ---------------- figure ----------------
    colors = {3: "tab:blue", 5: "tab:green", 7: "tab:orange", 9: "tab:purple"}
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(7.0, 7.6), sharex=True)

    for R in R_LIST:
        ax1.semilogy(wt, np.maximum(Delta(results[R]), 1e-16),
                     color=colors[R], lw=1.0, label=rf"KvN-QSVT $(R={R})$")
    ax1.semilogy(wt, np.maximum(Delta(x_dir), 1e-16), "k--", lw=1.8, zorder=5,
                 label=r"exact $e^{-i\hat{H}_m\tau}$ (direct propagation)")
    ax1.semilogy(wt, np.maximum(Delta(x_exp), 1e-16), color="0.55", ls="-.",
                 lw=1.2, label="KvN-expm (per-step re-encoding)")
    ax1.set_ylim(1e-3, 3)
    ax1.set_ylabel(r"$\Delta(t)$", fontsize=13)
    ax1.legend(fontsize=8.5, ncol=2, loc="lower right")
    ax1.grid(True, which="both", ls="--", lw=0.5)

    for R in R_LIST:
        ax2.semilogy(wt[1:], np.maximum(dev(results[R], x_dir)[1:], 1e-16),
                     color=colors[R], lw=1.3, label=rf"$R={R}$")
    ax2.semilogy(wt[1:], np.maximum(dev(x_orig, x_dir)[1:], 1e-16),
                 color="0.4", ls=":", lw=1.3,
                 label="original phase files (deg. 4/5)")
    ax2.set_xlabel(r"$\omega_{p,e}\,t$", fontsize=13)
    ax2.set_ylabel(r"$\|\mathbf{x}_{R}-\mathbf{x}_{\mathrm{exact}}\|"
                   r"/\|\mathbf{x}_{\mathrm{exact}}\|$", fontsize=12)
    ax2.legend(fontsize=9.5, loc="center right")
    ax2.grid(True, which="both", ls="--", lw=0.5)

    fig.tight_layout()
    out = "output/CaseBC/1DAdvectionTest_qsvt_R_dependence.pdf"
    fig.savefig(out, format="pdf")
    print("Saved:", out)


if __name__ == "__main__":
    main()
